
public enum Status
{
    LOADING_FAILURE,
    LOADING_SUCCESS,
    SETTING_FAILURE,
    SETTING_SUCCESS,
    ANIMATION_START,
    ANIMATION_END,
    INCORRECT_FORMAT,
    ALREADY_IN_PROGRESS,

    SCENE_STARTED
}
